name: Build and Release on Push

on:
  push:
    branches: [main]

permissions:
  contents: write

jobs:
  build-and-release:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - name: Install Swift (Linux)
        if: runner.os == 'Linux'
        uses: swift-actions/setup-swift@v2
        with:
          swift-version: "6.2"

      - name: Build
        run: swift build -c release --static-swift-stdlib

      - name: Prepare Artifact Name
        # Adds the OS name to the file so they don't collide in the Release
        run: |
          cp .build/release/liblightaskerlib.a liblightaskerlib-${{ runner.os }}.a

      - name: Release Assets
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ github.run_number }}
          name: Release v${{ github.run_number }}
          files: liblightaskerlib-${{ runner.os }}.a
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
